# Generated by Django 4.0.4 on 2022-05-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pro', models.IntegerField()),
                ('nom_pro', models.CharField(max_length=64)),
                ('des_pro', models.CharField(max_length=300)),
                ('pric_pro', models.CharField(max_length=30)),
                ('stock_pro', models.IntegerField()),
                ('desc_pro', models.IntegerField()),
                ('img_pro', models.ImageField(upload_to='img')),
                ('tipo', models.IntegerField()),
            ],
        ),
    ]
